[phases.setup]
nixPkgs = [
    "nodejs_18",
    "chromium",
    "libnss3",
    "at-spi2-core",
    "libdrm",
    "mesa",
    "cups",
    "libuuid",
    "libxkbcommon",
    "alsa-lib",
    "atk",
    "at-spi2-atk",
    "cairo",
    "dbus",
    "expat",
    "fontconfig",
    "freetype",
    "gdk-pixbuf",
    "glib",
    "gtk3",
    "nspr",
    "pango",
    "xorg.libX11",
    "xorg.libXcomposite",
    "xorg.libXdamage",
    "xorg.libXext",
    "xorg.libXfixes",
    "xorg.libXrandr",
    "xorg.libxcb"
]

[phases.build]
cmds = ["npm install"]

[variables]
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
PUPPETEER_EXECUTABLE_PATH = "/usr/bin/chromium"
NODE_ENV = "production"
